# Generated by Django 5.1.4 on 2024-12-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_seat_booking_seat_row_alter_booking_seat_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=3),
        ),
    ]
